### PR TITLE
Better heuristics for guessing source roots

### LINKED ISSUE #115: Source roots approximation is incorrect
I had a root directory in my workspace called java_hello. `WORKSPACE_ROOT/java_hello/src/main/java/com/hello/Hello.java`. 
The heuristics for detecting source roots found `java` in `java_hello` and inferred root to be `WORKSPACE_ROOT/java` - a directory which doesn't exist. Which resolved in package prefix `..java_hello.src.main.java.com.hello` instead of expected `com.hello`.
In fastpass we've been using following logic, which seemed to work fine:

```scala
  private val sourceRootPattern = FileSystems.getDefault.getPathMatcher(
    "glob:**/{main,test,tests,src,3rdparty,3rd_party,thirdparty,third_party}/{resources,scala,java,jvm,proto,python,protobuf,py}"
  )
  private val defaultTestRootPattern = FileSystems.getDefault.getPathMatcher(
    "glob:**/{test,tests}"
  )

  private def approximateSourceRoot(dir: Path): Option[Path] = {
    @tailrec def loop(d: Path): Option[Path] = {
      if (sourceRootPattern.matches(d)) Some(d)
      else if (defaultTestRootPattern.matches(d)) Some(d)
      else {
        Option(d.getParent) match {
          case Some(parent) => loop(parent)
          case None => None
        }
      }
    }
    loop(dir)
  }
```

Maybe it might be configurable. But actually it would be the best if bazel could provide this information.

### PR DESCRIPTION
**Pull request by odisseus**
Fixes #115.

Credits for the idea go to @lukaszwawrzyk.

### CODE REVIEW

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java [hunk 1]
```diff
@@ -161,31 +164,49 @@ public void onBuildExit() {
...
+              } catch (Exception e) {
+                throw new RuntimeException(e);
+              }
+            })
+            .map(serverBuildManager::getSourcesRoot)
+            .map(Uri::fromAbsolutePath)
+            .map(uri -> uri.toString())
+            .collect(Collectors.toSet());
+
+    return ImmutableList.copyOf(sourceRootUris);
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java:209]:
```suggestion
  private List<String> getRuleRoots(List<SourceItem> items) {
   return items.stream()
            .map(SourceItem ::getUri)
            .map(uri -> {
              try {
                URL url = new URL(uri);
                return url.toURI();
              } catch (Exception e) {
                throw new RuntimeException(e);
              }
            })
            .map(serverBuildManager::getSourcesRoot)
            .map(Uri::fromAbsolutePath)
            .map(Uri:toString)
            .distinct()
            .collect(Collectors.toList());
```

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java [hunk 2]
```diff
@@ -64,13 +64,32 @@ public BazelBspServerBuildManager(
...
+    PathMatcher defaultTestRootPattern = fs.getPathMatcher("glob:**/{test,tests}");
+    Path sourceRootGuess = null;
+    for (PathMatcher pattern : new PathMatcher[]{sourceRootPattern, defaultTestRootPattern}) {
+      sourceRootGuess = approximateSourceRoot(sourcePath, pattern);
+      if (sourceRootGuess != null) break;
+    }
+    if (sourceRootGuess == null) {
+      return sourcePath.getParent().toString();
+    }
+    return sourceRootGuess.toAbsolutePath().toString();
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java:83]:
```suggestion
Optional<Path> patternPath = ImmutableList.of(sourceRootPattern, defaultTestRootPattern).stream()
      .map(pattern -> approximateSourceRoot(sourcePath, pattern))
      .filter(Optional::isPresent)
      .map(Optional::get)
      .findFirst()
      .map(Path::toAbsolutePath);

  return patternPath.orElse(sourcePath.getParent())
      .toString();
```

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java [hunk 3]
```diff
@@ -64,13 +64,32 @@ public BazelBspServerBuildManager(
...
+  }
+
+  private Path approximateSourceRoot(Path dir, PathMatcher matcher) {
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java:86]: i believe that it would be better to use `Optional` and return `Empty` instead of `null`. Also, it would be more efficient to change recursion into a loop

**Review by abrams27 — CHANGES_REQUESTED** [review]
thanks a lot for the contribution!

i left some comments, also it would be nice to add some tests (I know you don't see a lot of tests now, but I'm trying to change that)

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java (hunk 1 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java]: Reformatted

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java (hunk 2 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java]: I think that my variant is more readable, even though it uses null.

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java (hunk 3 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java:89]: Removed the recursion. Also, I think it's okay to use null here, because this is just a private method, and only a few lines long. On the other hand, the `getParent` method may return null anyway, and I'd rather not introduce Java optionals just for the sake of it.

**Comment by odisseus** [comment]
I have extracted the source root heuristic into a separate class and added some test cases. What exactly should I write in the changelog?

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java (hunk 2 above)
Comment (abrams27) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java]: i strongly disagree - at least for me it looks very messy

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java [hunk 4]
```diff
@@ -161,31 +164,51 @@ public void onBuildExit() {
...
+                  try {
+                    URL url = new URL(uri);
+                    return url.toURI();
+                  } catch (Exception e) {
+                    throw new RuntimeException(e);
+                  }
+                })
+            .map(SourceRootGuesser::getSourcesRoot)
+            .map(Uri::fromAbsolutePath)
+            .map(uri -> uri.toString())
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java:208]: lambda could be replaced with a method reference

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java [hunk 5]
```diff
@@ -161,31 +164,51 @@ public void onBuildExit() {
...
 
-  private List<String> getRuleRoots(Build.Rule rule) {
-    String sourcesRootUriString = serverBuildManager.getSourcesRoot(rule.getName());
-    Uri uri = Uri.fromAbsolutePath(sourcesRootUriString);
-
-    return ImmutableList.of(uri.toString());
+  private List<String> getRuleRoots(List<SourceItem> items) {
+    Set<String> sourceRootUris =
+        items.stream()
+            .map(item -> item.getUri())
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java:196]: lambda could be replaced with a method reference

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java [hunk 6]
```diff
@@ -161,31 +164,51 @@ public void onBuildExit() {
...
+                  } catch (Exception e) {
+                    throw new RuntimeException(e);
+                  }
+                })
+            .map(SourceRootGuesser::getSourcesRoot)
+            .map(Uri::fromAbsolutePath)
+            .map(uri -> uri.toString())
+            .collect(Collectors.toSet());
+
+    return ImmutableList.copyOf(sourceRootUris);
```
Comment (abrams27) [inline server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java:211]: could be replaced by `.distinct()` (look previous version of review)

**Review by abrams27 — CHANGES_REQUESTED** [review]
one more thing from the previous review

---
> What exactly should I write in the changelog?

added better heuristics for guessing source roots / fixed heuristics for guessing source roots - whatever you prefer

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java (hunk 2 above)
Comment (jastice) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java]: Both are readable to me. I don't think we should make such style matters a big issue in accepting PRs ;)

Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BazelBspServerBuildManager.java]: Refactored

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java (hunk 5 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java]: Done

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java (hunk 4 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java]: Done

File: server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java (hunk 6 above)
Comment (odisseus) [reply server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/services/BuildServerService.java]: Done

**Review by abrams27 — APPROVED** [review]
Looks great! Thanks so much for the contribution, I really appreciate it!
